# Generated by Django 4.1.7 on 2023-04-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_tags_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
