# Generated by Django 4.1.7 on 2023-05-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_alter_todo_completed_spendtags_spend'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
