# Generated by Django 4.1.7 on 2023-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0010_spend_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
