# Generated by Django 4.1.7 on 2023-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0011_spend_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.CharField(blank=True, default='Нет', max_length=15, null=True),
        ),
    ]
