# Generated by Django 4.1.7 on 2023-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0012_notes_is_pinned_alter_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
